import os
import django
import sys

# Setup Django Environment
sys.path.append(os.getcwd())
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'cultural_advisor.settings')
django.setup()

from advisor.models import Etiquette

def populate_etiquette():
    data = [
        # --- INDIA & REGIONS ---
        {"country": "India", "region": "South Asia", "continent": "Asia", "capital_city": "New Delhi", "greeting_word": "Namaste", "greeting_gesture": "Joining palms (Anjali Mudra).", "communication_style": "Indirect and polite.", "communication_tips": "Avoid 'no' directly.", "dining_etiquette": "Right hand only.", "table_manners": "Wait for host.", "dress_code": "Conservative.", "gift_giving": "Sweets/Flowers.", "public_behavior": "Low PDA.", "business_meeting": "Building rapport.", "language": "Hindi/English", "basic_words": "Namaste", "pronunciation": "Phonetic", "dos": "Respect elders.", "donts": "Don't touch heads.", "tourist_tips": "Bottled water."},
        {"country": "Tamil Nadu", "region": "South India", "continent": "Asia", "capital_city": "Chennai", "greeting_word": "Vanakkam", "greeting_gesture": "Anjali Mudra.", "communication_style": "Humble/Scholarly.", "communication_tips": "Sir/Madam.", "dining_etiquette": "Banana leaf.", "table_manners": "Fingers.", "dress_code": "Traditional.", "gift_giving": "Sweets.", "public_behavior": "Temple ethics.", "business_meeting": "Formal.", "language": "Tamil", "basic_words": "Nandri", "pronunciation": "Soft.", "dos": "Temples.", "donts": "Shoes inside.", "tourist_tips": "Filter coffee."},
        {"country": "Kerala", "region": "South India", "continent": "Asia", "capital_city": "Trivandrum", "greeting_word": "Namaskaram", "greeting_gesture": "Bow/Hands together.", "communication_style": "Polite/Literate.", "communication_tips": "Direct yet soft.", "dining_etiquette": "Sadya feast.", "table_manners": "Fingers only.", "dress_code": "White/Cream Mundu.", "gift_giving": "Traditional.", "public_behavior": "Hygiene-conscious.", "business_meeting": "Clear.", "language": "Malayalam", "basic_words": "Nanni", "pronunciation": "Melodic.", "dos": "Ecology.", "donts": "Loudness.", "tourist_tips": "Backwaters."},
        {"country": "Karnataka", "region": "South India", "continent": "Asia", "capital_city": "Bengaluru", "greeting_word": "Namaskara", "greeting_gesture": "Joining hands.", "communication_style": "Moderate/Multilingual.", "communication_tips": "Be patient in traffic.", "dining_etiquette": "Filter coffee/Udupi.", "table_manners": "Fingers.", "dress_code": "Urban/Traditional.", "gift_giving": "Sandalwood.", "public_behavior": "Tech-savvy yet traditional.", "business_meeting": "Professional.", "language": "Kannada", "basic_words": "Dhanyavada", "pronunciation": "Clear.", "dos": "Respect local culture.", "donts": "Don't mock local lang.", "tourist_tips": "Hampi ruins."},
        {"country": "Andhra Pradesh", "region": "South India", "continent": "Asia", "capital_city": "Amaravati", "greeting_word": "Namaskaram", "greeting_gesture": "Joining hands.", "communication_style": "Vibrant/Spicy.", "communication_tips": "Hospitality is key.", "dining_etiquette": "Spicy cuisine.", "table_manners": "Shared meals.", "dress_code": "Traditional.", "gift_giving": "Kondapalli toys.", "public_behavior": "Respectful.", "business_meeting": "Enthusiastic.", "language": "Telugu", "basic_words": "Dhanyavadalu", "pronunciation": "Rhythmic.", "dos": "Eat spicy food.", "donts": "Don't waste water.", "tourist_tips": "Tirupati temple."},
        {"country": "Telangana", "region": "South India", "continent": "Asia", "capital_city": "Hyderabad", "greeting_word": "Salam / Namaskaram", "greeting_gesture": "Handshake/Namaste.", "communication_style": "Tehzeeb (Etiquette).", "communication_tips": "Respect Urdu influence.", "dining_etiquette": "Hyderabadi Biryani.", "table_manners": "Shared platters.", "dress_code": "Modern/Indo-Islamic.", "gift_giving": "Pearls.", "public_behavior": "Polite.", "business_meeting": "Formal.", "language": "Telugu/Urdu", "basic_words": "Shukriya", "pronunciation": "Soft.", "dos": "Try Biryani.", "donts": "Don't be rude.", "tourist_tips": "Charminar."},
        {"country": "Delhi", "region": "North India", "continent": "Asia", "capital_city": "New Delhi", "greeting_word": "Namaste", "greeting_gesture": "Handshake.", "communication_style": "Fast/Expressive.", "communication_tips": "Bargain at markets.", "dining_etiquette": "Mughlai.", "table_manners": "Modern.", "dress_code": "Cosmopolitan.", "gift_giving": "High-end sweets.", "public_behavior": "Alertness.", "business_meeting": "Networking.", "language": "Hindi/Punjabi", "basic_words": "Zaroor", "pronunciation": "Urban.", "dos": "Use Metro.", "donts": "Don't litter.", "tourist_tips": "Red Fort."},
        {"country": "Mumbai", "region": "West India", "continent": "Asia", "capital_city": "Mumbai", "greeting_word": "Hello / Namaste", "greeting_gesture": "Nod/Handshake.", "communication_style": "Business-fast.", "communication_tips": "Time is precious.", "dining_etiquette": "Vada Pav/Sea food.", "table_manners": "Quick.", "dress_code": "Western.", "gift_giving": "Traditional.", "public_behavior": "Commuter focus.", "business_meeting": "Corporate.", "language": "Marathi/Hindi", "basic_words": "Ho", "pronunciation": "Fast.", "dos": "Walk fast.", "donts": "Don't block doors.", "tourist_tips": "Marine Drive."},
        {"country": "Chennai", "region": "South India", "continent": "Asia", "capital_city": "Chennai", "greeting_word": "Vanakkam", "greeting_gesture": "Bow.", "communication_style": "Scholarly.", "communication_tips": "Conservative values.", "dining_etiquette": "Banana leaf.", "table_manners": "Fingers.", "dress_code": "Modest.", "gift_giving": "Flowers.", "public_behavior": "Calm.", "business_meeting": "Professional.", "language": "Tamil", "basic_words": "Ama", "pronunciation": "Tamilian.", "dos": "Punctual.", "donts": "No PDA.", "tourist_tips": "Marina Beach."},
        {"country": "Kolkata", "region": "East India", "continent": "Asia", "capital_city": "Kolkata", "greeting_word": "Namaskar", "greeting_gesture": "Joining hands.", "communication_style": "Intellectual/Poetic.", "communication_tips": "Discuss art/politics.", "dining_etiquette": "Sweets/Fish.", "table_manners": "Right hand.", "dress_code": "Simple/White.", "gift_giving": "Books/Sweets.", "public_behavior": "Creative.", "business_meeting": "Long talk.", "language": "Bengali", "basic_words": "Khub bhalo", "pronunciation": "Sweet.", "dos": "Try sweets.", "donts": "Don't be loud.", "tourist_tips": "Victoria Memorial."},

        # --- ASIA ---
        {"country": "Japan", "region": "East Asia", "continent": "Asia", "capital_city": "Tokyo", "greeting_word": "Konnichiwa", "greeting_gesture": "Bowing.", "communication_style": "Harmony (Wa).", "communication_tips": "Read the air.", "dining_etiquette": "Itadakimasu.", "table_manners": "Chopsticks vertically no.", "dress_code": "Neat.", "gift_giving": "Wrapping key.", "public_behavior": "No phone on trains.", "business_meeting": "Business cards with 2 hands.", "language": "Japanese", "basic_words": "Hai", "pronunciation": "Flat.", "dos": "Bow.", "donts": "No tipping.", "tourist_tips": "Kyoto shrines."},
        {"country": "China", "region": "East Asia", "continent": "Asia", "capital_city": "Beijing", "greeting_word": "Ni Hao", "greeting_gesture": "Nod/Handshake.", "communication_style": "Hierarchy/Face.", "communication_tips": "Respect seniority.", "dining_etiquette": "Lazy Susan.", "table_manners": "Wait for elder.", "dress_code": "Professional.", "gift_giving": "No clocks.", "public_behavior": "Stoic.", "business_meeting": "Build Guanxi.", "language": "Mandarin", "basic_words": "Xie Xie", "pronunciation": "Tonal.", "dos": "Both hands for gift.", "donts": "Don't lose face.", "tourist_tips": "Great Wall."},
        {"country": "South Korea", "region": "East Asia", "continent": "Asia", "capital_city": "Seoul", "greeting_word": "Annyeonghaseyo", "greeting_gesture": "Deep bow.", "communication_style": "Ranking based.", "communication_tips": "Respect age.", "dining_etiquette": "Don't lift bowl.", "table_manners": "Eldest starts.", "dress_code": "Fashionable.", "gift_giving": "Nicely wrapped.", "public_behavior": "Quiet in subway.", "business_meeting": "Exchanging cards.", "language": "Korean", "basic_words": "Kamsahamnida", "pronunciation": "Honorifics.", "dos": "Shoes off.", "donts": "Don't pour own drink.", "tourist_tips": "Gyeongbokgung."},
        {"country": "North Korea", "region": "East Asia", "continent": "Asia", "capital_city": "Pyongyang", "greeting_word": "Annyeonghasimnika", "greeting_gesture": "Bow.", "communication_style": "Formal.", "communication_tips": "Politics no.", "dining_etiquette": "Traditional.", "table_manners": "Stiff.", "dress_code": "Conservative.", "gift_giving": "Practical.", "public_behavior": "Disciplined.", "business_meeting": "State-led.", "language": "Korean", "basic_words": "Kamsamnida", "pronunciation": "Stronger accent.", "dos": "Follow guide.", "donts": "No unauthorized photos.", "tourist_tips": "Guided tours only."},
        {"country": "Singapore", "region": "Southeast Asia", "continent": "Asia", "capital_city": "Singapore", "greeting_word": "Hello", "greeting_gesture": "Handshake.", "communication_style": "Direct/Singlish.", "communication_tips": "Efficiency counts.", "dining_etiquette": "Hawker centers.", "table_manners": "Casual.", "dress_code": "Smart casual.", "gift_giving": "Not expected.", "public_behavior": "Strict rules.", "business_meeting": "Punctual.", "language": "English/Mandarin", "basic_words": "Thank you", "pronunciation": "Fast.", "dos": "Recycle.", "donts": "No chewing gum.", "tourist_tips": "Gardens by the Bay."},
        {"country": "Malaysia", "region": "Southeast Asia", "continent": "Asia", "capital_city": "Kuala Lumpur", "greeting_word": "Selamat Datang", "greeting_gesture": "Salam (touch hands/heart).", "communication_style": "Respectful mix.", "communication_tips": "Harmony focus.", "dining_etiquette": "Right hand fingers.", "table_manners": "Wash hands.", "dress_code": "Modest (Islamic culture).", "gift_giving": "Avoid alcohol.", "public_behavior": "Religious respect.", "business_meeting": "Formal.", "language": "Malay/English", "basic_words": "Terima Kasih", "pronunciation": "Melodic.", "dos": "Shoes off at mosque.", "donts": "Left hand food.", "tourist_tips": "Petronas Towers."},
        {"country": "Thailand", "region": "Southeast Asia", "continent": "Asia", "capital_city": "Bangkok", "greeting_word": "Sawadee", "greeting_gesture": "The Wai.", "communication_style": "Smile/Calm.", "communication_tips": "Don't raise voice.", "dining_etiquette": "Spoon/Fork.", "table_manners": "Share food.", "dress_code": "Modest in temples.", "gift_giving": "Fruit.", "public_behavior": "Feet low head high.", "business_meeting": "Rapport.", "language": "Thai", "basic_words": "Kob kun", "pronunciation": "Tonal.", "dos": "Respect King.", "donts": "Don't touch head.", "tourist_tips": "Grand Palace."},
        {"country": "Indonesia", "region": "Southeast Asia", "continent": "Asia", "capital_city": "Jakarta", "greeting_word": "Selamat", "greeting_gesture": "Handshake/Salam.", "communication_style": "Soft/Polite.", "communication_tips": "Hospitality emphasis.", "dining_etiquette": "Right hand.", "table_manners": "Shared meals.", "dress_code": "Batik.", "gift_giving": "Traditional.", "public_behavior": "Religious norms.", "business_meeting": "Social first.", "language": "Indonesian", "basic_words": "Terima Kasih", "pronunciation": "Clear.", "dos": "Be patient (Jam Karet).", "donts": "Public PDA.", "tourist_tips": "Bali beaches."},
        {"country": "Philippines", "region": "Southeast Asia", "continent": "Asia", "capital_city": "Manila", "greeting_word": "Kumusta", "greeting_gesture": "Handshake/Pagmamano.", "communication_style": "Warm/Friendly.", "communication_tips": "Hospitality/Family.", "dining_etiquette": "Kamayan (eating with hands).", "table_manners": "Abundant food.", "dress_code": "Barong/Filipiniana.", "gift_giving": "Pasalubong.", "public_behavior": "Social.", "business_meeting": "Personal rapport.", "language": "Filipino/English", "basic_words": "Salamat", "pronunciation": "Phonetic.", "dos": "Be polite.", "donts": "Don't be impatient.", "tourist_tips": "Palawan islands."},
        {"country": "Vietnam", "region": "Southeast Asia", "continent": "Asia", "capital_city": "Hanoi", "greeting_word": "Xin Chao", "greeting_gesture": "Bow/Handshake.", "communication_style": "Respectful.", "communication_tips": "Value hierarchy.", "dining_etiquette": "Chopsticks.", "table_manners": "Hold bowl.", "dress_code": "Modest.", "gift_giving": "Tea/Fruit.", "public_behavior": "Diligence.", "business_meeting": "Cards with 2 hands.", "language": "Vietnamese", "basic_words": "Cam on", "pronunciation": "Tonal.", "dos": "Remove shoes.", "donts": "No politics.", "tourist_tips": "Ha Long Bay."},
        {"country": "Sri Lanka", "region": "South Asia", "continent": "Asia", "capital_city": "Colombo", "greeting_word": "Ayubowan", "greeting_gesture": "Joining hands.", "communication_style": "Gentle/Polite.", "communication_tips": "Smile often.", "dining_etiquette": "Rice and Curry.", "table_manners": "Right hand.", "dress_code": "Saree/Sarong.", "gift_giving": "Tea/Fruit.", "public_behavior": "Religious focus.", "business_meeting": "Rapport.", "language": "Sinhala/Tamil", "basic_words": "Stuti", "pronunciation": "Soft.", "dos": "Temples.", "donts": "No shorts in temples.", "tourist_tips": "Tea estates."},
        {"country": "Nepal", "region": "South Asia", "continent": "Asia", "capital_city": "Kathmandu", "greeting_word": "Namaste", "greeting_gesture": "Hands together.", "communication_style": "Pious/Soft.", "communication_tips": "Value traditions.", "dining_etiquette": "Dal Bhat.", "table_manners": "Juto (pollution) avoid.", "dress_code": "Modest/Warm.", "gift_giving": "Traditional.", "public_behavior": "Peaceful.", "business_meeting": "Social start.", "language": "Nepali", "basic_words": "Dhanyavad", "pronunciation": "Clear.", "dos": "Respect mountains.", "donts": "No beef.", "tourist_tips": "Everest base camp."},
        {"country": "Bangladesh", "region": "South Asia", "continent": "Asia", "capital_city": "Dhaka", "greeting_word": "Assalamu Alaikum", "greeting_gesture": "Salam/Handshake.", "communication_style": "Welcoming/Direct.", "communication_tips": "Hospitality.", "dining_etiquette": "Spicy/Fish.", "table_manners": "Right hand.", "dress_code": "Traditional.", "gift_giving": "Sweets.", "public_behavior": "Busy.", "business_meeting": "Formal.", "language": "Bengali", "basic_words": "Dhonnobad", "pronunciation": "Sweet.", "dos": "Eat with hand.", "donts": "No politics.", "tourist_tips": "Sundarbans."},
        {"country": "Pakistan", "region": "South Asia", "continent": "Asia", "capital_city": "Islamabad", "greeting_word": "Assalamu Alaikum", "greeting_gesture": "Handshake/Hug.", "communication_style": "Poetic/Respectful.", "communication_tips": "Respect elders.", "dining_etiquette": "Dastarkhwan.", "table_manners": "Shared platters.", "dress_code": "Shalwar Kameez.", "gift_giving": "Traditional.", "public_behavior": "Hospitable.", "business_meeting": "Formal.", "language": "Urdu/English", "basic_words": "Shukriya", "pronunciation": "Soft.", "dos": "Respect Ramadan.", "donts": "Left hand food.", "tourist_tips": "Northern areas."},

        # --- MIDDLE EAST ---
        {"country": "UAE", "region": "Middle East", "continent": "Asia", "capital_city": "Abu Dhabi", "greeting_word": "Salam", "greeting_gesture": "Handshake.", "communication_style": "Hospitable.", "communication_tips": "Wait for coffee.", "dining_etiquette": "Dates/Coffee.", "table_manners": "Right hand.", "dress_code": "Modest.", "gift_giving": "Dates.", "public_behavior": "Strict laws.", "business_meeting": "Trust based.", "language": "Arabic", "basic_words": "Shukran", "pronunciation": "Clear.", "dos": "Observe Ramadan.", "donts": "No PDA.", "tourist_tips": "Burj Khalifa."},
        {"country": "Dubai", "region": "Middle East", "continent": "Asia", "capital_city": "Dubai", "greeting_word": "Salam", "greeting_gesture": "Handshake.", "communication_style": "Modern/Islamic.", "communication_tips": "Luxury/Speed.", "dining_etiquette": "Global.", "table_manners": "Formal.", "dress_code": "Stylish/Modest.", "gift_giving": "Gold/Perfume.", "public_behavior": "Rule-focus.", "business_meeting": "Flashy.", "language": "Arabic/English", "basic_words": "Marhaba", "pronunciation": "Soft.", "dos": "Respect culture.", "donts": "No alcohol in public.", "tourist_tips": "Dubai Mall."},
        {"country": "Saudi Arabia", "region": "Middle East", "continent": "Asia", "capital_city": "Riyadh", "greeting_word": "Salam", "greeting_gesture": "Kisses/Hands.", "communication_style": "Traditional.", "communication_tips": "Religion centric.", "dining_etiquette": "Shared plate.", "table_manners": "Hospitality.", "dress_code": "Abaya/Thobe.", "gift_giving": "Incense.", "public_behavior": "Prayer times.", "business_meeting": "Slow.", "language": "Arabic", "basic_words": "Sami", "pronunciation": "Deep.", "dos": "Cover up.", "donts": "No photos of women/military.", "tourist_tips": "Medina."},
        {"country": "Qatar", "region": "Middle East", "continent": "Asia", "capital_city": "Doha", "greeting_word": "Salam", "greeting_gesture": "Handshake.", "communication_style": "Refined.", "communication_tips": "Status/Wealth.", "dining_etiquette": "Majlis.", "table_manners": "Polite.", "dress_code": "Very modest.", "gift_giving": "Luxury.", "public_behavior": "Calm.", "business_meeting": "Formal.", "language": "Arabic", "basic_words": "Afwan", "pronunciation": "Soft.", "dos": "Hospitality.", "donts": "No offensive talk.", "tourist_tips": "Museum of Islamic Art."},
        {"country": "Oman", "region": "Middle East", "continent": "Asia", "capital_city": "Muscat", "greeting_word": "Salam", "greeting_gesture": "Nose touch (trad).", "communication_style": "Friendly.", "communication_tips": "Nature lovers.", "dining_etiquette": "Omani Halwa.", "table_manners": "Generous.", "dress_code": "Traditional.", "gift_giving": "Daggers (Khanjar).", "public_behavior": "Peaceful.", "business_meeting": "Steady.", "language": "Arabic", "basic_words": "Zain", "pronunciation": "Soft.", "dos": "Respect nature.", "donts": "Don't rush.", "tourist_tips": "Wadis."},
        {"country": "Kuwait", "region": "Middle East", "continent": "Asia", "capital_city": "Kuwait City", "greeting_word": "Salam", "greeting_gesture": "Handshake.", "communication_style": "Strong family focus.", "communication_tips": "Discussion focus.", "dining_etiquette": "Diwaniya.", "table_manners": "Traditional.", "dress_code": "Western/Trad mix.", "gift_giving": "Sweets.", "public_behavior": "Social.", "business_meeting": "Formal.", "language": "Arabic", "basic_words": "Aywa", "pronunciation": "Clear.", "dos": "Be guest-friendly.", "donts": "No disrespect.", "tourist_tips": "Kuwait Towers."},

        # --- EUROPE ---
        {"country": "France", "region": "Europe", "continent": "Europe", "capital_city": "Paris", "greeting_word": "Bonjour", "greeting_gesture": "La Bise.", "communication_style": "Formal.", "communication_tips": "Start with Bonjour.", "dining_etiquette": "Long meals.", "table_manners": "Bread on table.", "dress_code": "Chic.", "gift_giving": "Wine/Flowers.", "public_behavior": "Moderate volume.", "business_meeting": "Vous form.", "language": "French", "basic_words": "Merci", "pronunciation": "Nasal.", "dos": "Learn basics.", "donts": "No rush waiter.", "tourist_tips": "Eiffel Tower."},
        {"country": "Germany", "region": "Europe", "continent": "Europe", "capital_city": "Berlin", "greeting_word": "Guten Tag", "greeting_gesture": "Firm handshake.", "communication_style": "Direct/Honest.", "communication_tips": "Absolute punctuality.", "dining_etiquette": "Fork/Knife.", "table_manners": "No fingers.", "dress_code": "Practical/Pro.", "gift_giving": "Chocolates.", "public_behavior": "Follow rules.", "business_meeting": "Agenda based.", "language": "German", "basic_words": "Danke", "pronunciation": "Guttural.", "dos": "Recycle.", "donts": "No war jokes.", "tourist_tips": "Brandenburg Gate."},
        {"country": "Italy", "region": "Europe", "continent": "Europe", "capital_city": "Rome", "greeting_word": "Ciao", "greeting_gesture": "Hug/Kisses.", "communication_style": "Passionate.", "communication_tips": "Gesticulate.", "dining_etiquette": "Many courses.", "table_manners": "No cappuccino after 11AM.", "dress_code": "Bella Figura.", "gift_giving": "Wine.", "public_behavior": "Sociable.", "business_meeting": "Rapport.", "language": "Italian", "basic_words": "Grazie", "pronunciation": "Musical.", "dos": "Dress well.", "donts": "No pineapple on pizza.", "tourist_tips": "Colosseum."},
        {"country": "Spain", "region": "Europe", "continent": "Europe", "capital_city": "Madrid", "greeting_word": "Hola", "greeting_gesture": "Two kisses.", "communication_style": "Warm/Late night.", "communication_tips": "Value family.", "dining_etiquette": "Tapas/Paella.", "table_manners": "Late meals.", "dress_code": "Stylish.", "gift_giving": "Flowers/Sweets.", "public_behavior": "Lively.", "business_meeting": "Lunch focus.", "language": "Spanish", "basic_words": "Gracias", "pronunciation": "Clear.", "dos": "Take siesta.", "donts": "Don't eat early.", "tourist_tips": "Sagrada Familia."},
        {"country": "UK", "region": "Europe", "continent": "Europe", "capital_city": "London", "greeting_word": "Hello", "greeting_gesture": "Handshake.", "communication_style": "Queuing/Polite.", "communication_tips": "Sorry often.", "dining_etiquette": "Pub culture.", "table_manners": "Polite.", "dress_code": "Smart casual.", "gift_giving": "Modest.", "public_behavior": "Queue focus.", "business_meeting": "Punctual.", "language": "English", "basic_words": "Cheers", "pronunciation": "Varies.", "dos": "Stay in line.", "donts": "No loudness.", "tourist_tips": "Big Ben."},
        {"country": "Netherlands", "region": "Europe", "continent": "Europe", "capital_city": "Amsterdam", "greeting_word": "Hallo", "greeting_gesture": "3 Kisses friend.", "communication_style": "Direct/Equal.", "communication_tips": "No fluff.", "dining_etiquette": "Early dinner.", "table_manners": "Pragmatic.", "dress_code": "Cycle-friendly.", "gift_giving": "Tulips.", "public_behavior": "Tolerant.", "business_meeting": "Consensus.", "language": "Dutch", "basic_words": "Dank", "pronunciation": "Throaty.", "dos": "Cycle.", "donts": "No arrogance.", "tourist_tips": "Canals."},
        {"country": "Switzerland", "region": "Europe", "continent": "Europe", "capital_city": "Bern", "greeting_word": "Gruezi", "greeting_gesture": "Handshake.", "communication_style": "Neutral/Reserved.", "communication_tips": "Punctuality extreme.", "dining_etiquette": "Fondue.", "table_manners": "Polite.", "dress_code": "High-end.", "gift_giving": "Chocolate.", "public_behavior": "Quiet/Private.", "business_meeting": "Efficiency.", "language": "German/French/Italian", "basic_words": "Merci", "pronunciation": "Clear.", "dos": "Be on time.", "donts": "No noise on Sundays.", "tourist_tips": "Swiss Alps."},

        # --- AMERICA ---
        {"country": "USA", "region": "America", "continent": "Americas", "capital_city": "Washington DC", "greeting_word": "Hello", "greeting_gesture": "Firm Handshake.", "communication_style": "Direct/Direct.", "communication_tips": "Time is Money.", "dining_etiquette": "Tipping mandatory.", "table_manners": "Abundant portions.", "dress_code": "Urban casual.", "gift_giving": "Open immediately.", "public_behavior": "Bubble space.", "business_meeting": "Efficiency.", "language": "English", "basic_words": "Hi", "pronunciation": "Varies.", "dos": "Tip 20%.", "donts": "No politics talk.", "tourist_tips": "Grand Canyon."},
        {"country": "Canada", "region": "America", "continent": "Americas", "capital_city": "Ottawa", "greeting_word": "Hello", "greeting_gesture": "Handshake.", "communication_style": "Polite/Sorry.", "communication_tips": "Multicultural.", "dining_etiquette": "Maple syrup.", "table_manners": "Tipping.", "dress_code": "Warm.", "gift_giving": "Small gifts.", "public_behavior": "Kindness.", "business_meeting": "Collaborative.", "language": "English/French", "basic_words": "Pardon", "pronunciation": "Soft.", "dos": "Hold doors.", "donts": "Don't confuse with US.", "tourist_tips": "Niagara Falls."},
        {"country": "Mexico", "region": "America", "continent": "Americas", "capital_city": "Mexico City", "greeting_word": "Hola", "greeting_gesture": "Hug/Kisses.", "communication_style": "Familiar.", "communication_tips": "Family first.", "dining_etiquette": "Late dinner.", "table_manners": "Spicy focus.", "dress_code": "Colorful.", "gift_giving": "High quality.", "public_behavior": "Sociable.", "business_meeting": "Rapport focus.", "language": "Spanish", "basic_words": "Gracias", "pronunciation": "Clear.", "dos": "Eat spicy.", "donts": "No water from tap.", "tourist_tips": "Chichen Itza."},
        {"country": "Brazil", "region": "America", "continent": "Americas", "capital_city": "Brasilia", "greeting_word": "Oi", "greeting_gesture": "Beijos.", "communication_style": "Energetic.", "communication_tips": "Physical touch.", "dining_etiquette": "Churrasco.", "table_manners": "Utensils always.", "dress_code": "Flashy.", "gift_giving": "Social.", "public_behavior": "Street parties.", "business_meeting": "Flexible time.", "language": "Portuguese", "basic_words": "Obrigado", "pronunciation": "Nasal.", "dos": "Be warm.", "donts": "No Spanish.", "tourist_tips": "Amazon."},

        # --- OCEANIA ---
        {"country": "Australia", "region": "Oceania", "continent": "Oceania", "capital_city": "Canberra", "greeting_word": "G'day", "greeting_gesture": "Friendly handshake.", "communication_style": "Informal.", "communication_tips": "Fair go.", "dining_etiquette": "Barbie culture.", "table_manners": "Relaxed.", "dress_code": "Casual.", "gift_giving": "Beer/Wine.", "public_behavior": "Easygoing.", "business_meeting": "Direct.", "language": "English", "basic_words": "Mate", "pronunciation": "Vowel stretch.", "dos": "Apply sunscreen.", "donts": "Don't brag.", "tourist_tips": "Barrier Reef."},
        {"country": "New Zealand", "region": "Oceania", "continent": "Oceania", "capital_city": "Wellington", "greeting_word": "Kia Ora", "greeting_gesture": "Hongi.", "communication_style": "Modest.", "communication_tips": "Maori respect.", "dining_etiquette": "Hangi.", "table_manners": "Polite.", "dress_code": "Comfortable.", "gift_giving": "Small items.", "public_behavior": "Eco-focus.", "business_meeting": "Egalitarian.", "language": "English/Maori", "basic_words": "Kia Ora", "pronunciation": "Kiwi.", "dos": "Nature hikes.", "donts": "Littering.", "tourist_tips": "Milford Sound."},

        # --- REGIONS ---
        {"country": "South Asia", "region": "Asia", "continent": "Asia", "capital_city": "N/A", "greeting_word": "Namaste/Salam", "greeting_gesture": "Hands joined.", "communication_style": "Respectful.", "communication_tips": "Community focus.", "dining_etiquette": "Shared food.", "table_manners": "Right hand.", "dress_code": "Modest.", "gift_giving": "Sweets.", "public_behavior": "Religious.", "business_meeting": "Relationship first.", "language": "Multiple", "basic_words": "Hello", "pronunciation": "Diverse.", "dos": "Be polite.", "donts": "No pork/beef focus.", "tourist_tips": "Ancient sites."},
        {"country": "Southeast Asia", "region": "Asia", "continent": "Asia", "capital_city": "N/A", "greeting_word": "Sawadee/Salamat", "greeting_gesture": "Bow/Smile.", "communication_style": "Soft/Peaceful.", "communication_tips": "Smile culture.", "dining_etiquette": "Street food.", "table_manners": "Informal.", "dress_code": "Tropical modest.", "gift_giving": "Fruit.", "public_behavior": "Relaxed.", "business_meeting": "Social bond.", "language": "Diverse", "basic_words": "Thank you", "pronunciation": "Tonal mix.", "dos": "Respect Monks.", "donts": "Touch heads.", "tourist_tips": "Islands/Jungles."},
        {"country": "Europe Region", "region": "Europe", "continent": "Europe", "capital_city": "N/A", "greeting_word": "Hello/Bonjour", "greeting_gesture": "Handshake.", "communication_style": "Structured.", "communication_tips": "Punctuality.", "dining_etiquette": "Formal dining.", "table_manners": "Utensils.", "dress_code": "Chic/Formal.", "gift_giving": "Wine/Flowers.", "public_behavior": "Quiet.", "business_meeting": "Efficient.", "language": "Diverse", "basic_words": "Merci/Danke", "pronunciation": "Varies.", "dos": "History travel.", "donts": "Skip queues.", "tourist_tips": "Eurail pass."},
        {"country": "Asia Region", "region": "Asia", "continent": "Asia", "capital_city": "N/A", "greeting_word": "Ni Hao/Namaste", "greeting_gesture": "Bow/Hands.", "communication_style": "Hierarchy focus.", "communication_tips": "Respect age.", "dining_etiquette": "Chopsticks/Hands.", "table_manners": "Share platter.", "dress_code": "Modest.", "gift_giving": "Respectful.", "public_behavior": "Traditional.", "business_meeting": "Rapport.", "language": "Diverse", "basic_words": "Hello", "pronunciation": "Varies.", "dos": "Explore history.", "donts": "Offend culture.", "tourist_tips": "Spirituality."},
        {"country": "Middle East Region", "region": "ME", "continent": "Asia", "capital_city": "N/A", "greeting_word": "Salam", "greeting_gesture": "Handshake.", "communication_style": "Hospitable.", "communication_tips": "Hospitality respect.", "dining_etiquette": "Shared plates.", "table_manners": "Right hand.", "dress_code": "Modest.", "gift_giving": "Gifts for host.", "public_behavior": "Religious respect.", "business_meeting": "Social bond.", "language": "Arabic", "basic_words": "Shukran", "pronunciation": "Guttural.", "dos": "Respect Ramadan.", "donts": "No public affection.", "tourist_tips": "Deserts/Souqs."}
    ]

    # Duplicate handling
    aliases = {
        "United States": "USA",
        "United Kingdom": "UK",
        "England": "UK",
        "United Arab Emirates": "UAE"
    }
    
    # Add aliases
    for alias, core in aliases.items():
        core_data = next((d for d in data if d["country"] == core), None)
        if core_data:
            data.append({**core_data, "country": alias})

    count = 0
    for entry in data:
        # CLEAN UP DUPLICATES BEFORE INSERTING
        Etiquette.objects.filter(country=entry['country']).delete()
        Etiquette.objects.create(**entry)
        count += 1
        
    print(f"Total Etiquette records synchronized: {count}")

if __name__ == "__main__":
    populate_etiquette()
