# Generated by Django 5.1.4 on 2026-03-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etiquette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('situation', models.CharField(max_length=100)),
                ('advice', models.TextField()),
            ],
        ),
    ]
