# Generated by Django 5.1.4 on 2026-03-14 07:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquette',
            name='body_language',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='business_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='communication_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiquette',
            name='dining_tip',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='do_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='dont_list',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='dress_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='greeting_pronunciation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='greeting_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='language',
            field=models.CharField(default='tamil', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiquette',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
