# Generated by Django 5.1.4 on 2026-03-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_etiquette_body_language_etiquette_business_tip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquette',
            name='advice',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='body_language',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='business_tip',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='communication_tip',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='dining_tip',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='do_list',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='dont_list',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='greeting_pronunciation',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='language',
        ),
        migrations.RemoveField(
            model_name='etiquette',
            name='situation',
        ),
        migrations.AddField(
            model_name='etiquette',
            name='basic_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='communication_tips',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='dining_etiquette',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='donts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='dos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='greeting_gesture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='etiquette',
            name='dress_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
