# Generated by Django 5.1.4 on 2026-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_remove_etiquette_advice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquette',
            name='language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='pronunciation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
