# Generated by Django 5.1.4 on 2026-03-15 06:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0004_etiquette_language_etiquette_pronunciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquette',
            name='business_meeting',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='capital_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='communication_style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etiquette',
            name='gift_giving',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='public_behavior',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='table_manners',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='tourist_tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
