# Generated by Django 5.2.12 on 2026-03-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0006_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquette',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='flag_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='official_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
