# Generated by Django 5.2.12 on 2026-03-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0007_etiquette_currency_etiquette_flag_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='flag_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
