# Generated by Django 5.2.12 on 2026-03-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0008_chatsession_flag_sent_chatsession_last_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquette',
            name='eating_style',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='education_dress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='famous_festivals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='festival_culture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='gift_culture_specific',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='marriage_dress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etiquette',
            name='traditional_food',
            field=models.TextField(blank=True, null=True),
        ),
    ]
