# Generated by Django 5.2.12 on 2026-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0009_etiquette_eating_style_etiquette_education_dress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etiquette',
            name='country',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
