# Generated by Django 5.2.12 on 2026-04-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0010_alter_etiquette_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_name', models.CharField(choices=[('GEMINI', 'Google Gemini AI'), ('REST_COUNTRIES', 'REST Countries API'), ('WIKIPEDIA', 'Wikipedia')], max_length=50)),
                ('endpoint', models.CharField(max_length=255)),
                ('query', models.TextField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=True)),
                ('latency', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'API Logs',
            },
        ),
    ]
